# fly.toml app configuration file generated for blue-tracker on 2025-06-20T17:05:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blue-tracker'
primary_region = 'dfw'

[build]

[mounts]
  source = "db_volume"
  destination = "data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
